### ISSUE TITLE
Medium article used your code

### ISSUE THREAD

**Issue by ashwin4ever** [Achronus/Machine-Learning-101#2]
Hello Achronus,

I came across this [https://towardsdatascience.com/analyzing-ad-monetization-techniques-using-reinforcement-learning-b091e2b3124c](url) medium article about Reinforcement Learning and the code posted in the article seems to be lifted from your repo. I understand your big heart in giving free usage rights but I want your work to be credited. I have seen numerous repos being taken down as they have been plagiarized by such authors. I have since made a comment on the article to credit the original author. Do note that in the medium article, the author has replaced `ads_ctr.values[n,ad]` instead of `dataset.values[n,ad]` for `Thompson Sampling`

**Comment by Achronus** [comment]
Hey ashwin4ever,

Thank you for letting me know. I appreciate your concern but honestly, it does not matter. I created this repository as an introduction to Machine Learning (ML), giving people that are interested in the field an opportunity to get a taste for it. The reason the code is completely reusable is because its at a very basic level. I strongly believe that all knowledge should be shared as people with different views and outlooks may create something incredible that can help push our world further. 

In terms of the article, as with any algorithm it is likely that a lot of people will use similar code. As Thompson Sampling is a big algorithm in the Reinforcement Learning space it doesn't surprise me that the code is very similar/identical. As I am currently in academia I understand that is very important to reference other authors work but in this instance I do not feel that adding me as a reference will be beneficial to anyone. If anything, I'd be inclined to request them to reference Stanfords tutorial on Thompson Sampling - https://web.stanford.edu/~bvr/pubs/TS_Tutorial.pdf.

I will close this issue as I do not feel any further action is needed. However, I would like to thank you again for bringing it to my attention.

All the best,
Achronus
